version: '2'

services:
    # search engine
    # elasticsearch:
    #     image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    #     container_name: elasticsearch
    #     entrypoint:
    #         - elasticsearch
    #         - -Ehttp.port=9200
    #         - -Ehttp.cors.enabled=true
    #         - -Ehttp.cors.allow-origin=http://localhost:1358
    #         - -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
    #         - -Ehttp.cors.allow-credentials=true
    #     user: elasticsearch
    #     ports:
    #         - "9200:9200"

    # elasticsearch browser
    # dejavu:
    #     image: appbaseio/dejavu:3.0.0-alpha
    #     container_name: dejavu
    #     ports:
    #         - "1358:1358"
    #     links:
    #         - elasticsearch

    db:
        image: mysql:5.7.17
        volumes:
            - "./.data/db:/var/lib/mysql"
            - /var/www:/var/www
#            - /var/www/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"           
        dns:
            - 172.22.33.10
            - 172.22.255.102
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION    

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:mysql
            
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./.data/mongo:/data/db               
    
    php:
        build: php7-fpm
        ports:
            - "9000:9000"
        dns:
            - 172.22.33.10
            - 172.22.255.102
        volumes:
            - /var/www:/var/www
            - ./logs/nlotv:/var/www/nlotv/app/logs
            - ./logs/indigo:/var/www/indigo/app/logs
            - ./logs/videomanager:/var/www/videomanager/var/logs
            - ./logs/ukraine:/var/www/ukraine/app/logs
            - ./logs/segodnya2018:/var/www/segodnya2018/var/logs
        links:
          - db
          - mongo
          - redis
          # - elasticsearch

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    redis-admin:
        image: faktiva/php-redis-admin
        environment:
            - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
        ports:
            - "8081:80"
        depends_on:
            - redis             

    nginx:
        build: nginx
        ports:
            - "80:80"
        volumes_from:
            - php:rw
        volumes:    
            - ./logs/nginx/:/var/log/nginx
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/sites/:/etc/nginx/sites-enabled
            - ./nginx/sites/:/etc/nginx/sites-available
        restart: always    

    # elk:
    #     image: willdurand/elk
    #     ports:
    #         - "81:80"
    #     volumes:
    #         - ./elk/logstash:/etc/logstash
    #         - ./elk/logstash/patterns:/opt/logstash/patterns
    #     volumes_from:
    #         - php
    #         - nginx
