version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
            - /var/www:/var/www
        ports:
            - "3306:3306"           
        dns:
            - 172.22.33.10
            - 172.22.255.102
        command: --default-authentication-plugin=mysql_native_password
        # command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION    
        restart: always    
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:mysql
            
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./.data/mongo:/data/db               
    
    php:
        build: php7-fpm
        ports:
            - "9000:9000"
        dns:
            - 172.22.33.10
            - 172.22.255.102
        volumes:
            - /var/www:/var/www
            # - ./logs/nlotv:/var/www/nlotv/var/logs
            # - ./logs/indigo:/var/www/indigo/var/logs
            # - ./logs/videomanager:/var/www/videomanager/var/logs
            # - ./logs/ukraine:/var/www/ukraine/var/logs
            # - ./logs/segodnya2018:/var/www/segodnya2018/var/logs
        links:
          - db
          - mongo
          - redis

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    redis-admin:
        image: faktiva/php-redis-admin
        environment:
            - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
        ports:
            - "8081:80"
        depends_on:
            - redis             

    nginx:
        build: nginx
        ports:
            - "80:80"
        volumes_from:
            - php:rw
        volumes:    
            - ./logs/nginx/:/var/log/nginx
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/sites/:/etc/nginx/sites-enabled
            - ./nginx/sites/:/etc/nginx/sites-available
        restart: always
